{{- define "ffc-helm-library.azure-ingress-master.tpl" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | default "nginx" | quote }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    {{- if not .Values.pr }}
    nginx.org/mergeable-ingress-type: "master"
    {{- end }}
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  {{- if .Values.pr }}
  - host: {{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}
  {{ else }}
  - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
  {{- end }}
{{ else }}
  - http:
{{- end }}
{{- end }}
{{- define "ffc-helm-library.azure-ingress-master" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.azure-ingress-master.tpl") -}}
{{- end -}}
