{{- define "ffc-helm-library.azure-identity.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ required (printf $requiredMsg "azureIdentity.name") .Values.azureIdentity.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
spec:
  type: 0
  resourceID: {{ required (printf $requiredMsg "azureIdentity.resourceID") .Values.azureIdentity.resourceID | quote }}
  clientID: {{ required (printf $requiredMsg "azureIdentity.clientID") .Values.azureIdentity.clientID | quote }}
{{- end -}}
{{- define "ffc-helm-library.azure-identity" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.azure-identity.tpl") -}}
{{- end -}}
