{{- define "ffc-helm-library.azure-identity-binding.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ required (printf $requiredMsg "azureIdentityBinding.name") .Values.azureIdentityBinding.name | quote }}
spec:
  azureIdentity: {{ required (printf $requiredMsg "azureIdentity.name") .Values.azureIdentity.name | quote }}
  selector: {{ required (printf $requiredMsg "azureIdentityBinding.selector") .Values.azureIdentityBinding.selector | quote }}
{{- end -}}
{{- define "ffc-helm-library.azure-identity-binding" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.azure-identity-binding.tpl") -}}
{{- end -}}
  