{{- define "ffc-helm-library.basic-auth-secret.tpl" -}}
{{- if .Values.auth }}
apiVersion: v1
data:
  auth: {{ quote .Values.auth }}
kind: Secret
metadata:
  name: ffc-demo-basic-auth
  namespace: {{ quote .Values.namespace }}
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
type: Opaque
{{- end }}
{{- end }}
{{- define "ffc-helm-library.basic-auth-secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.basic-auth-secret.tpl") -}}
{{- end -}}
