{{- define "ffc-helm-library.cluster-ip-service.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ required (printf $requiredMsg "container.port") .Values.container.port }}
  selector:
    {{- include "ffc-helm-library.selector-labels" . | nindent 4 }}
{{- end -}}
{{- define "ffc-helm-library.cluster-ip-service" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.cluster-ip-service.tpl") -}}
{{- end -}}
