{{- define "ffc-helm-library.cluster-ip-service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ffc-helm-library.checkRequired.tpl" (list . "name" .Values.name) | quote }}
  namespace: {{ include "ffc-helm-library.checkRequired.tpl" (list . "namespace" .Values.namespace) | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ include "ffc-helm-library.checkRequired.tpl" (list . "container.port" .Values.container.port) }}
  selector:
    {{- include "ffc-helm-library.selectorLabels" . | nindent 4 }}
{{- end -}}
{{- define "ffc-helm-library.cluster-ip-service" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.cluster-ip-service.tpl") -}}
{{- end -}}
