{{- define "ffc-helm-library.container-config-map.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
data:
{{- if (.Values.azureIdentity) }}
  AZURE_CLIENT_ID: {{ required (printf $requiredMsg "azureIdentity.clientID") .Values.azureIdentity.clientID | quote }}
{{- end }}
{{- end }}
{{- define "ffc-helm-library.container-config-map" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.container-config-map.tpl") -}}
{{- end -}}
