{{- define "ffc-helm-library.container-config-map.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
data: {}
{{- end }}
{{- define "ffc-helm-library.container-config-map" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.container-config-map.tpl") -}}
{{- end -}}
