{{- define "ffc-helm-library.container-secret.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required (printf $requiredMsg "containerSecret.name") .Values.containerSecret.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
type: {{ required (printf $requiredMsg "containerSecret.type") .Values.containerSecret.type | quote }}
data: {}
{{- end }}
{{- define "ffc-helm-library.container-secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.container-secret.tpl") -}}
{{- end -}}
