{{- define "ffc-helm-library.container-secret.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
type: {{ .Values.containerSecret.type | default "Opaque" | quote }}
data: {}
{{- end }}
{{- define "ffc-helm-library.container-secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.container-secret.tpl") -}}
{{- end -}}
