{{- define "ffc-helm-library.cron-job.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
    {{- if and (.Values.azureIdentity) (.Values.workloadIdentity) }}
    azure.workload.identity/use: "true"
    {{- end }}
spec:
  schedule: {{ required (printf $requiredMsg "cronJob.schedule") .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ required (printf $requiredMsg "cronJob.concurrencyPolicy") .Values.cronJob.concurrencyPolicy | quote }}
  jobTemplate: 
    spec:
      template:
        metadata:
          labels:
            {{- include "ffc-helm-library.labels" . | nindent 12 }}
            {{- if and (.Values.azureIdentity) (.Values.workloadIdentity) }}
            azure.workload.identity/use: "true"
            {{- else if .Values.azureIdentity }}
            aadpodidbinding: {{ .Chart.Name }}-identity-selector
            {{- end }}
        spec:
          restartPolicy: {{ .Values.cronJob.restartPolicy | default "Always" | quote }}
          securityContext:
            fsGroup: {{ .Values.cronJob.runAsUser | default 1000 }}
            runAsUser: {{ .Values.cronJob.runAsUser | default 1000 }}
            runAsNonRoot: {{ .Values.cronJob.runAsNonRoot | default true }}
          volumes:
          - name: temp-dir
            emptyDir: {}
          containers:
          {{- if .Values.container }}
          - {{ include "ffc-helm-library.container" (list . (printf "%s.container" .Chart.Name )) | nindent 12 }}
          {{- else }}
          -
          {{- end }}
{{- end }}
{{- define "ffc-helm-library.cron-job" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.cron-job.tpl") -}}
{{- end -}}
