{{- define "ffc-helm-library.eks-service-account.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required (printf $requiredMsg "serviceAccount.name") .Values.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required (printf $requiredMsg "serviceAccount.roleArn") .Values.serviceAccount.roleArn  | quote }}
{{- end }}
{{- define "ffc-helm-library.eks-service-account" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.eks-service-account.tpl") -}}
{{- end -}}
