{{- define "ffc-helm-library.rolebinding.tpl" -}}
{{- if not .Values.ingress.alb }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.auth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ffc-demo-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ffc-demo"
{{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override {{.Values.name }}.default.svc.cluster.local:{{ .Values.service.port }};
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
  name: {{ quote .Values.name }}
  namespace: {{ quote .Values.namespace }}
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
    http:
{{ else }}
  - http:
{{- end }}
      paths:
      - path: /?(.*)
        backend:
          serviceName: {{ quote .Values.name }}
          servicePort: {{ .Values.service.port }}
{{- end }}
{{- end }}
{{- define "ffc-helm-library.ingress" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.ingress.tpl") -}}
{{- end -}}
