{{- define "ffc-helm-library.persistent-volume.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required (printf $requiredMsg "PersistentVolumeClaim.name") .Values.PersistentVolumeClaim.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace  | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.size | quote }}
  storageClassName: {{ required (printf $requiredMsg "PersistentVolumeClaim.storageClassName") .Values.PersistentVolumeClaim.storageClassName | quote }}
  volumeName: {{ required (printf $requiredMsg "PersistentVolumeClaim.volumeName") .Values.PersistentVolumeClaim.volumeName | quote }}
{{- end }}
{{- define "ffc-helm-library.persistent-volume" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.persistent-volume.tpl") -}}
{{- end -}}
