{{- define "ffc-helm-library.postgres-service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.postgresService.postgresHost }}
  namespace: {{ quote .Values.namespace }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ quote .Values.postgresService.postgresExternalName }}
  ports:
    - name: port
      port: {{ .Values.postgresService.postgresPort }}
{{- end -}}
{{- define "ffc-helm-library.postgres-service" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.postgres-service.tpl") -}}
{{- end -}}
