{{- define "ffc-helm-library.rolebinding.tpl" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-developer-1-admin-rolebinding
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.workstream }}-developer-1
{{- end -}}
{{- define "ffc-helm-library.rolebinding" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.rolebinding.tpl") -}}
{{- end -}}
