{{- define "ffc-helm-library.role-binding.tpl" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-developer-1-admin-rolebinding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Release.Namespace }}-developer-1
{{- end -}}
{{- define "ffc-helm-library.role-binding" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.role-binding.tpl") -}}
{{- end -}}
