{{- define "ffc-helm-library.secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ quote .Values.secret.name }}
  namespace: {{ quote .Values.namespace }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
type: {{ quote .Values.secret.type }}
data:
  auth: {{ quote .Values.auth }}
{{- end }}
{{- define "ffc-helm-library.secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.secret.tpl") -}}
{{- end -}}
