{{- define "ffc-helm-library.secret-provider-class.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  provider: "azure"
  parameters:
    usePodIdentity: {{ .Values.secretProviderClass.azure.usePodIdentity | default "false" | quote }}
    clientID: {{ .Values.azureIdentity.clientID | default "placeholder-clientID" | quote }}
    keyvaultName: {{ .Values.secretProviderClass.azure.keyvaultName | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.azure.objects }}
        - |
          objectName: {{ .objectName | quote }}
          objectType: {{ .objectType | default "secret" | quote }}
          {{- if .objectVersion }}
          objectVersion: {{ .objectVersion | quote }}
          {{- end }}
        {{- end }}
    tenantId: {{ .Values.secretProviderClass.azure.tenantId | default "placeholder-tenantId" | quote }}
  {{- if .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- range .Values.secretProviderClass.secretObjects }}
    - secretName: {{ .secretName | quote }}
      type: {{ .type | default "Opaque" | quote }}
      data:
        {{- range .data }}
        - objectName: {{ .objectName | quote }}
          key: {{ .key | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- define "ffc-helm-library.secret-provider-class" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.secret-provider-class.tpl") -}}
{{- end -}}