{{- define "ffc-helm-library.secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ffc-helm-library.checkRequired.tpl" (list . "secret.name" .Values.secret.name) | quote }}
  namespace: {{ include "ffc-helm-library.checkRequired.tpl" (list . "namespace" .Values.namespace) | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
type: {{ include "ffc-helm-library.checkRequired.tpl" (list . "secret.type" .Values.secret.type) | quote }}
data: {}
{{- end }}
{{- define "ffc-helm-library.secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.secret.tpl") -}}
{{- end -}}
