{{- define "ffc-helm-library.secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
type: {{ .Values.secret.type | default "Opaque" | quote }}
data: {}
{{- end }}
{{- define "ffc-helm-library.secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.secret.tpl") -}}
{{- end -}}
