{{- define "ffc-helm-library.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.name }}
  namespace: {{ quote .Values.namespace }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  type: {{ quote .Values.service.type }}
{{- end -}}
{{- define "ffc-helm-library.service" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.service.tpl") -}}
{{- end -}}
