{{- define "ffc-helm-library.service-account.tpl" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ quote .Values.serviceAccount.name }}
  namespace: {{ quote .Values.namespace }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ quote .Values.serviceAccount.roleArn }}
{{- end }}
{{- define "ffc-helm-library.service-account" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.service-account.tpl") -}}
{{- end -}}
