{{- define "ffc-helm-library.service-account.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and (.Values.azureIdentity) (.Values.workloadIdentity) }}
  annotations:
    azure.workload.identity/client-id: {{ required (printf $requiredMsg "azureIdentity.clientID") .Values.azureIdentity.clientID | quote }}
  {{- end -}}
  name: {{ .Chart.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
{{- end }}
{{- define "ffc-helm-library.service-account" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.service-account.tpl") -}}
{{- end -}}
