{{- define "ffc-helm-library.service.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote}}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec:
  type: {{ required (printf $requiredMsg "service.type") .Values.service.type | quote }}
{{- end -}}
{{- define "ffc-helm-library.service" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.service.tpl") -}}
{{- end -}}
