{{- define "ffc-helm-library.service-account.tpl" -}}
{{- if .Values.serviceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ quote .Values.serviceAccount.name }}
  namespace: {{ quote .Values.namespace }}
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ quote .Values.serviceAccount.roleArn }}
{{- end }}
{{- end }}
{{- define "ffc-helm-library.service-account" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.service-account.tpl") -}}
{{- end -}}
