{{- define "ffc-helm-library.service-account.tpl" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.name | quote }}
  namespace: {{ .Release.Name  | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
{{- end }}
{{- define "ffc-helm-library.service-account" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.service-account.tpl") -}}
{{- end -}}
