{{- define "ffc-helm-library.tls-secret.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
type: "kubernetes.io/tls"
data:
  tls.crt: {{ .Values.tlsSecret.cert | b64enc | quote }}
  tls.key: {{ .Values.tlsSecret.key | b64enc | quote }}
{{- end }}
{{- define "ffc-helm-library.tls-secret" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.tls-secret.tpl") -}}
{{- end -}}
