{{- define "ffc-helm-library.vertical-pod-autoscaler.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata: 
  name: {{ .Chart.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
spec: 
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.name | quote }}
  updatePolicy: 
    updateMode: {{ required (printf $requiredMsg "updateMode") .Values.deployment.updateMode }}
{{- end }}
{{- define "ffc-helm-library.vertical-pod-autoscaler" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.vertical-pod-autoscaler.tpl") -}}
{{- end -}}

