{{- define "adp-helm-library.azure-ingress-master.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{  required (printf $requiredMsg ".ingress.class") .Values.ingress.class | quote }}
    {{- if eq .Values.ingress.class "nginx" }}
    nginx.org/client-max-body-size: 1024m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    {{- if not .Values.pr }}
    nginx.org/mergeable-ingress-type: "master"
    {{- end }}
    {{- end }}
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  {{- if .Values.pr }}
  - host: {{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}
  {{ else }}
  - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
  {{- end }}
{{ else }}
  - http:
{{- end }}
{{- end }}
{{- define "adp-helm-library.azure-ingress-master" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.azure-ingress-master.tpl") -}}
{{- end -}}
