{{- define "adp-helm-library.horizontal-pod-autoscaler.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  minReplicas: {{ required (printf $requiredMsg "minReplicas") .Values.deployment.minReplicas }}
  maxReplicas: {{ required (printf $requiredMsg "maxReplicas") .Values.deployment.maxReplicas }}
{{- end }}
{{- define "adp-helm-library.horizontal-pod-autoscaler" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.horizontal-pod-autoscaler.tpl") -}}
{{- end -}}
