{{- define "adp-helm-library.ingress.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{  required (printf $requiredMsg ".ingress.class") .Values.ingress.class | quote }}
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  {{- if .Values.pr }}
  - host: {{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}
  {{ else }}
  - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
  {{- end }}
    http:
{{ else }}
  - http:
{{- end }}
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
            port:
              number: 80
{{- end }}
{{- define "adp-helm-library.ingress" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.ingress.tpl") -}}
{{- end -}}
