{{- define "adp-helm-library.persistent-volume-claim.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required (printf $requiredMsg "persistentVolumeClaim.name") .Values.persistentVolumeClaim.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace  | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size | quote }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName | default "" }}
{{- end }}
{{- define "adp-helm-library.persistent-volume-claim" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.persistent-volume-claim.tpl") -}}
{{- end -}}
