{{- define "adp-helm-library.postgres-service.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ required (printf $requiredMsg "postgresService.postgresHost") .Values.postgresService.postgresHost | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ required (printf $requiredMsg "postgresService.postgresExternalName") .Values.postgresService.postgresExternalName | quote }}
  ports:
    - name: port
      port: {{ required (printf $requiredMsg "postgresService.postgresPort") .Values.postgresService.postgresPort }}
{{- end -}}
{{- define "adp-helm-library.postgres-service" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.postgres-service.tpl") -}}
{{- end -}}
