{{- define "adp-helm-library.role-binding.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name }}-developer-1-admin-rolebinding
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ required (printf $requiredMsg "namespace") .Values.namespace }}-developer-1
{{- end -}}
{{- define "adp-helm-library.role-binding" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.role-binding.tpl") -}}
{{- end -}}
