{{- define "adp-helm-library.service-account.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required (printf $requiredMsg "serviceAccount.name") .Values.serviceAccount.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace  | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
{{- end }}
{{- define "adp-helm-library.service-account" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.service-account.tpl") -}}
{{- end -}}
